version: '3.8'

services: 
    web:
        build: .
        command: python3 /home/mateusz/django_projects/mbs/medical_booking_system/manage.py runserver 0.0.0.0:8000
        volumes: 
            - .:/home/mateusz/django_projects/mbs/medical_booking_system/
        ports: 
            - 8000:8000
        depends_on: 
            - db
    db:
        image: postgres:11
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
volumes: 
    postgres_data: