# Generated by Django 3.0.7 on 2020-06-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorschedule',
            name='occupied',
            field=models.BooleanField(default=False),
        ),
    ]
