# Generated by Django 3.0.7 on 2020-06-20 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_datetime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DateTime',
        ),
    ]
