# Generated by Django 3.0.7 on 2020-06-20 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_doctorvisitdate_doctorvisittime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.DoctorVisitDate'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.DoctorVisitTime'),
        ),
    ]
